/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAL.ConnectionDB_DAL;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.LinkedList;
/**
 *
 * @author Huy
 */
public class Login_GUI extends javax.swing.JFrame {

    
    /** Creates new form Login_GUI */
    
    public Login_GUI() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        SignInButton = new javax.swing.JLabel();
        SignInLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        PasswordField = new javax.swing.JPasswordField();
        PassLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IDLabel = new javax.swing.JLabel();
        IDTextField = new javax.swing.JTextField();
        RightLable = new javax.swing.JLabel();
        SideLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(740, 530));
        setPreferredSize(new java.awt.Dimension(730, 539));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignInButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/button.png"))); // NOI18N
        SignInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignInButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignInButtonMouseExited(evt);
            }
        });
        mainPanel.add(SignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, 70));

        SignInLabel.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        SignInLabel.setForeground(new java.awt.Color(148, 181, 247));
        SignInLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignInLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/Sign-in.png"))); // NOI18N
        SignInLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.add(SignInLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 380, 490));
        mainPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 310, 20));

        PasswordField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PasswordField.setText(".............");
        PasswordField.setBorder(null);
        PasswordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PasswordField.setOpaque(false);
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        mainPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 310, 40));

        PassLabel.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        PassLabel.setForeground(new java.awt.Color(148, 181, 247));
        PassLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassLabel.setText("PASSWORD");
        mainPanel.add(PassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 140, 80));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 310, 20));

        IDLabel.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        IDLabel.setForeground(new java.awt.Color(148, 181, 247));
        IDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDLabel.setText("ID");
        mainPanel.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 80, 80));

        IDTextField.setFont(new java.awt.Font("UTM Avo", 1, 12)); // NOI18N
        IDTextField.setText("Enter your ID");
        IDTextField.setBorder(null);
        IDTextField.setOpaque(false);
        IDTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDTextFieldFocusLost(evt);
            }
        });
        mainPanel.add(IDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 310, 50));

        RightLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RightLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/sideRight.png"))); // NOI18N
        mainPanel.add(RightLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 400, 500));

        SideLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SideLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/sideLeft.png"))); // NOI18N
        mainPanel.add(SideLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, -1, 500));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseEntered
        // TODO add your handling code here:
        SignInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/button_enter.png")));
    }//GEN-LAST:event_SignInButtonMouseEntered

    private void IDTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusGained
        // TODO add your handling code here:
        if(IDTextField.getText().equals("Enter your ID")){
            IDTextField.setText("");
        }
    }//GEN-LAST:event_IDTextFieldFocusGained

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        // TODO add your handling code here:
        if(PasswordField.getText().equals(".............")){
            PasswordField.setText("");
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void SignInButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseExited
        // TODO add your handling code here:
        SignInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/button.png")));
    }//GEN-LAST:event_SignInButtonMouseExited

    private void IDTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDTextFieldFocusLost
        // TODO add your handling code here:
        if(IDTextField.getText().isEmpty()) {
            IDTextField.setText("Enter your ID");
        }
    }//GEN-LAST:event_IDTextFieldFocusLost

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        // TODO add your handling code here:
        if(PasswordField.getText().isEmpty()) {
            PasswordField.setText(".............");
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    private void SignInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseClicked
//        if (conection.OpenConnection()){
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
        this.setVisible(false);
    //    }
    }//GEN-LAST:event_SignInButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
              
            }
        });
    }
    public static ConnectionDB_DAL conection = new ConnectionDB_DAL();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RightLable;
    private javax.swing.JLabel SideLable;
    private javax.swing.JLabel SignInButton;
    private javax.swing.JLabel SignInLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

}
