/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.Employee_BUS;
import DAL.Employee_DAL;
import DTO.Employee_DTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author Huy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {

        initComponents();
        setLocationRelativeTo(null);
        Phong_Table.getTableHeader().setFont(new Font("UTM Avo", Font.BOLD, 12));
        KH_Table.getTableHeader().setFont(new Font("UTM Avo", Font.BOLD, 12));
        NV_Table.getTableHeader().setFont(new Font("UTM Avo", Font.BOLD, 12));
        LSDP_Table.getTableHeader().setFont(new Font("UTM Avo", Font.BOLD, 12));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        btnINFO = new javax.swing.JLabel();
        LogoLable = new javax.swing.JLabel();
        btnLSDP = new javax.swing.JLabel();
        btnQLP = new javax.swing.JLabel();
        btnQLKH = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JLabel();
        btnDX = new javax.swing.JLabel();
        BackGr = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        TabPanel = new javax.swing.JTabbedPane();
        Main_Panel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        Info_Panel = new javax.swing.JPanel();
        SDT_Text = new javax.swing.JLabel();
        SDT_Backgr = new javax.swing.JLabel();
        ID_Text = new javax.swing.JLabel();
        ID_Backgr = new javax.swing.JLabel();
        Name_Text = new javax.swing.JLabel();
        Name_Backgr = new javax.swing.JLabel();
        btnDMK = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        QLP_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        TypeRoomComboBox = new javax.swing.JComboBox<>();
        ID_TextField = new javax.swing.JTextField();
        BookID_TextField = new javax.swing.JTextField();
        CustomerID_TextField = new javax.swing.JTextField();
        btnFind_P = new javax.swing.JLabel();
        btnBook_P = new javax.swing.JLabel();
        btnUpdate_P = new javax.swing.JLabel();
        btnCheckIn_P = new javax.swing.JLabel();
        btnCheckOut_P = new javax.swing.JLabel();
        btnClear_P = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Phong_Table = new javax.swing.JTable();
        KH_Panel = new javax.swing.JPanel();
        btnClear_KH = new javax.swing.JLabel();
        btnFind_KH = new javax.swing.JLabel();
        btnAdd_KH = new javax.swing.JLabel();
        btnUpdate_KH = new javax.swing.JLabel();
        btnDelete_KH = new javax.swing.JLabel();
        DOBirth_KH_TextField = new javax.swing.JTextField();
        CCCD_KH_TextField = new javax.swing.JTextField();
        Phone_KH_TextField = new javax.swing.JTextField();
        Name_KH_TextField = new javax.swing.JTextField();
        CusID_TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KH_Table = new javax.swing.JTable();
        NV_Panel = new javax.swing.JPanel();
        btnClear_NV = new javax.swing.JLabel();
        btnFind_NV = new javax.swing.JLabel();
        btnAdd_NV = new javax.swing.JLabel();
        btnUpdate_NV = new javax.swing.JLabel();
        btnDelete_NV = new javax.swing.JLabel();
        DePart_NV_TextField = new javax.swing.JComboBox<>();
        DOBirth_NV_TextField = new javax.swing.JTextField();
        Phone_NV_TextField = new javax.swing.JTextField();
        Adr_NV_TextField = new javax.swing.JTextField();
        Gender_NV_TextField = new javax.swing.JTextField();
        Name_NV_TextField = new javax.swing.JTextField();
        StaffID_TextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        NV_Table = new javax.swing.JTable();
        LSDP_Panel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        LSDP_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOTEL MANAGEMENT");
        setBackground(new java.awt.Color(250, 249, 248));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnINFO.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnINFO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnINFO1.png"))); // NOI18N
        btnINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnINFOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnINFOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnINFOMouseExited(evt);
            }
        });
        mainPanel.add(btnINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 70));

        LogoLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/logoMainForm.png"))); // NOI18N
        LogoLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoLableMouseClicked(evt);
            }
        });
        mainPanel.add(LogoLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 190));

        btnLSDP.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnLSDP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLSDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnLSP1.png"))); // NOI18N
        btnLSDP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLSDPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLSDPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLSDPMouseExited(evt);
            }
        });
        mainPanel.add(btnLSDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 260, 70));

        btnQLP.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnQLP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQLP1.png"))); // NOI18N
        btnQLP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLPMouseExited(evt);
            }
        });
        mainPanel.add(btnQLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 260, 70));

        btnQLKH.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnQLKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQKH1.png"))); // NOI18N
        btnQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLKHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLKHMouseExited(evt);
            }
        });
        mainPanel.add(btnQLKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 260, 70));

        btnQLNV.setFont(new java.awt.Font("UTM Avo", 0, 14)); // NOI18N
        btnQLNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQNV1.png"))); // NOI18N
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQLNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQLNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQLNVMouseExited(evt);
            }
        });
        mainPanel.add(btnQLNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 260, 70));

        btnDX.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        btnDX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnDX1.png"))); // NOI18N
        btnDX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDXMouseExited(evt);
            }
        });
        mainPanel.add(btnDX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, -1, -1));

        BackGr.setBackground(new java.awt.Color(250, 249, 248));
        BackGr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/Background1.png"))); // NOI18N
        mainPanel.add(BackGr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 900));

        header.setBackground(new java.awt.Color(250, 249, 248));
        header.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        header.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mainPanel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 30));

        Main_Panel.setBackground(new java.awt.Color(250, 249, 248));
        Main_Panel.setMinimumSize(new java.awt.Dimension(935, 872));
        Main_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        Main_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/MainTab.png"))); // NOI18N
        Main_Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 900));

        TabPanel.addTab("tab7", Main_Panel);

        Info_Panel.setBackground(new java.awt.Color(250, 249, 248));
        Info_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        Info_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SDT_Text.setBackground(new java.awt.Color(250, 249, 248));
        SDT_Text.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        SDT_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SDT_Text.setText("Your Phone Number");
        SDT_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SDT_Text.setOpaque(true);
        Info_Panel.add(SDT_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 610, 50));

        SDT_Backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/SDT_Backgr.png"))); // NOI18N
        Info_Panel.add(SDT_Backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 800, 60));

        ID_Text.setBackground(new java.awt.Color(250, 249, 248));
        ID_Text.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        ID_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID_Text.setText("Your ID");
        ID_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ID_Text.setOpaque(true);
        Info_Panel.add(ID_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 610, 50));

        ID_Backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/ID_Backgr.png"))); // NOI18N
        Info_Panel.add(ID_Backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 800, 60));

        Name_Text.setBackground(new java.awt.Color(250, 249, 248));
        Name_Text.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        Name_Text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_Text.setText("Your Full Name");
        Name_Text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Name_Text.setOpaque(true);
        Info_Panel.add(Name_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 610, 50));

        Name_Backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/Name_Backgr.png"))); // NOI18N
        Info_Panel.add(Name_Backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 800, 60));

        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnDMK1.png"))); // NOI18N
        btnDMK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        btnDMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDMKMouseExited(evt);
            }
        });
        Info_Panel.add(btnDMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 260, 70));

        jLabel2.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("INFO");
        Info_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, 60));

        TabPanel.addTab("tab1", Info_Panel);

        QLP_Panel.setBackground(new java.awt.Color(250, 249, 248));
        QLP_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        QLP_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ROOM MANAGEMENT");
        QLP_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 300, 70));

        StatusComboBox.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Available", "Check In", "Booked", "Repairing" }));
        StatusComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(StatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 390, 40));

        TypeRoomComboBox.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        TypeRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "VIP", "Standard", "Double", "Single", "Twin", "Triple" }));
        TypeRoomComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        QLP_Panel.add(TypeRoomComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 390, 40));

        ID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        ID_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ID_TextField.setText("Room ID");
        ID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ID_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ID_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ID_TextFieldFocusLost(evt);
            }
        });
        QLP_Panel.add(ID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 390, 40));

        BookID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        BookID_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BookID_TextField.setText("Booking ID");
        BookID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BookID_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BookID_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BookID_TextFieldFocusLost(evt);
            }
        });
        QLP_Panel.add(BookID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 390, 40));

        CustomerID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        CustomerID_TextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CustomerID_TextField.setText("Customer ID");
        CustomerID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CustomerID_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CustomerID_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CustomerID_TextFieldFocusLost(evt);
            }
        });
        QLP_Panel.add(CustomerID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 390, 40));

        btnFind_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind1.png"))); // NOI18N
        btnFind_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnFind_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFind_PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFind_PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFind_PMouseExited(evt);
            }
        });
        QLP_Panel.add(btnFind_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 260, 50));

        btnBook_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnBook1.png"))); // NOI18N
        btnBook_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnBook_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBook_PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBook_PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBook_PMouseExited(evt);
            }
        });
        QLP_Panel.add(btnBook_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 120, 50));

        btnUpdate_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd1.png"))); // NOI18N
        btnUpdate_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnUpdate_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate_PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdate_PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdate_PMouseExited(evt);
            }
        });
        QLP_Panel.add(btnUpdate_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 120, 50));

        btnCheckIn_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnCkIN1.png"))); // NOI18N
        btnCheckIn_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnCheckIn_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckIn_PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckIn_PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckIn_PMouseExited(evt);
            }
        });
        QLP_Panel.add(btnCheckIn_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 120, 50));

        btnCheckOut_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnCkO1.png"))); // NOI18N
        btnCheckOut_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnCheckOut_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckOut_PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckOut_PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckOut_PMouseExited(evt);
            }
        });
        QLP_Panel.add(btnCheckOut_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 120, 50));

        btnClear_P.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        btnClear_P.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear_P.setText("Clear");
        btnClear_P.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        QLP_Panel.add(btnClear_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 260, 50));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("dd/mm/yyyy");
        jLabel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jLabel25.setOpaque(true);
        QLP_Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 390, 40));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/ChekIN_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 540, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/CusID_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 540, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/BookID_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 540, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/Status_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 540, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/TypeRoom_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 540, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/ID_Bgr.png"))); // NOI18N
        QLP_Panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 540, 50));

        Phong_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Type Of Room", "Status", "Booking ID", "Customer ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Phong_Table.setFocusable(false);
        Phong_Table.setOpaque(false);
        Phong_Table.setRowHeight(25);
        Phong_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Phong_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Phong_Table.getTableHeader().setResizingAllowed(false);
        Phong_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Phong_Table);

        QLP_Panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 880, 460));

        TabPanel.addTab("tab2", QLP_Panel);

        KH_Panel.setBackground(new java.awt.Color(250, 249, 248));
        KH_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        KH_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClear_KH.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        btnClear_KH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear_KH.setText("Clear");
        btnClear_KH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        KH_Panel.add(btnClear_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 120, 50));

        btnFind_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind1.png"))); // NOI18N
        btnFind_KH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnFind_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFind_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFind_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFind_KHMouseExited(evt);
            }
        });
        KH_Panel.add(btnFind_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 260, 50));

        btnAdd_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnAdd1.png"))); // NOI18N
        btnAdd_KH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnAdd_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd_KHMouseExited(evt);
            }
        });
        KH_Panel.add(btnAdd_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 120, 50));

        btnUpdate_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd1.png"))); // NOI18N
        btnUpdate_KH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnUpdate_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdate_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdate_KHMouseExited(evt);
            }
        });
        KH_Panel.add(btnUpdate_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 120, 50));

        btnDelete_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnDel1.png"))); // NOI18N
        btnDelete_KH.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnDelete_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelete_KHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete_KHMouseExited(evt);
            }
        });
        KH_Panel.add(btnDelete_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 120, 50));

        DOBirth_KH_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        DOBirth_KH_TextField.setText("Date Of Birth");
        DOBirth_KH_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DOBirth_KH_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBirth_KH_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBirth_KH_TextFieldFocusLost(evt);
            }
        });
        KH_Panel.add(DOBirth_KH_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 380, 40));

        CCCD_KH_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        CCCD_KH_TextField.setText("CCCD");
        CCCD_KH_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CCCD_KH_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CCCD_KH_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CCCD_KH_TextFieldFocusLost(evt);
            }
        });
        KH_Panel.add(CCCD_KH_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 380, 40));

        Phone_KH_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        Phone_KH_TextField.setText("Phone Number");
        Phone_KH_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Phone_KH_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Phone_KH_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Phone_KH_TextFieldFocusLost(evt);
            }
        });
        KH_Panel.add(Phone_KH_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 380, 40));

        Name_KH_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        Name_KH_TextField.setText("Full Name");
        Name_KH_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Name_KH_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Name_KH_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Name_KH_TextFieldFocusLost(evt);
            }
        });
        KH_Panel.add(Name_KH_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 380, 40));

        CusID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        CusID_TextField.setText("Customer ID");
        CusID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        CusID_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CusID_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CusID_TextFieldFocusLost(evt);
            }
        });
        KH_Panel.add(CusID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 380, 40));

        jLabel8.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel8.setText("CUSTOMER MANAGEMENT");
        KH_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 330, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/CusID_Bgr.png"))); // NOI18N
        KH_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 540, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/DateOfBirth_Bgr.png"))); // NOI18N
        KH_Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 540, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/Name_Bgr.png"))); // NOI18N
        KH_Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 540, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/Phone_Bgr.png"))); // NOI18N
        KH_Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 540, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/CCCD_Bgr.png"))); // NOI18N
        KH_Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 540, 50));

        KH_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Full Name", "CCCD", "Phone Number", "Date Of Birth"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KH_Table.setRowHeight(25);
        KH_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        KH_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        KH_Table.getTableHeader().setResizingAllowed(false);
        KH_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(KH_Table);

        KH_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 880, 510));

        TabPanel.addTab("tab4", KH_Panel);

        NV_Panel.setBackground(new java.awt.Color(250, 249, 248));
        NV_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        NV_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClear_NV.setFont(new java.awt.Font("UTM Avo", 1, 14)); // NOI18N
        btnClear_NV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClear_NV.setText("Clear");
        btnClear_NV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        NV_Panel.add(btnClear_NV, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 120, 50));

        btnFind_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind1.png"))); // NOI18N
        btnFind_NV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnFind_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFind_NVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFind_NVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFind_NVMouseExited(evt);
            }
        });
        NV_Panel.add(btnFind_NV, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 260, 50));

        btnAdd_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnAdd1.png"))); // NOI18N
        btnAdd_NV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnAdd_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd_NVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd_NVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd_NVMouseExited(evt);
            }
        });
        NV_Panel.add(btnAdd_NV, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 120, 50));

        btnUpdate_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd1.png"))); // NOI18N
        btnUpdate_NV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnUpdate_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate_NVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdate_NVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdate_NVMouseExited(evt);
            }
        });
        NV_Panel.add(btnUpdate_NV, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 120, 50));

        btnDelete_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnDel1.png"))); // NOI18N
        btnDelete_NV.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnDelete_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelete_NVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete_NVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete_NVMouseExited(evt);
            }
        });
        NV_Panel.add(btnDelete_NV, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 120, 50));

        DePart_NV_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        DePart_NV_TextField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cleaner", "Security Guard", "Room Attendent", "Receptionist", "Manager" }));
        DePart_NV_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        NV_Panel.add(DePart_NV_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 390, 40));

        DOBirth_NV_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        DOBirth_NV_TextField.setText("Date Of Birth");
        DOBirth_NV_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DOBirth_NV_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBirth_NV_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBirth_NV_TextFieldFocusLost(evt);
            }
        });
        NV_Panel.add(DOBirth_NV_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 390, 40));

        Phone_NV_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        Phone_NV_TextField.setText("Phone Number");
        Phone_NV_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Phone_NV_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Phone_NV_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Phone_NV_TextFieldFocusLost(evt);
            }
        });
        NV_Panel.add(Phone_NV_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 390, 40));

        Adr_NV_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        Adr_NV_TextField.setText("Address");
        Adr_NV_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Adr_NV_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Adr_NV_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Adr_NV_TextFieldFocusLost(evt);
            }
        });
        NV_Panel.add(Adr_NV_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 390, 40));

        Gender_NV_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        Gender_NV_TextField.setText("Gender");
        Gender_NV_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Gender_NV_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Gender_NV_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Gender_NV_TextFieldFocusLost(evt);
            }
        });
        NV_Panel.add(Gender_NV_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 390, 40));

        Name_NV_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        Name_NV_TextField.setText("Full Name");
        Name_NV_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Name_NV_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Name_NV_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Name_NV_TextFieldFocusLost(evt);
            }
        });
        NV_Panel.add(Name_NV_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 390, 40));

        StaffID_TextField.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        StaffID_TextField.setText("Staff ID");
        StaffID_TextField.setAlignmentX(10.0F);
        StaffID_TextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        StaffID_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                StaffID_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                StaffID_TextFieldFocusLost(evt);
            }
        });
        NV_Panel.add(StaffID_TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 390, 40));

        jLabel14.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel14.setText("EMPLOYEE MANAGEMENT");
        NV_Panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 380, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLNV_pic/DePart_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 540, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLNV_pic/StaffID_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 540, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/Name_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 540, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLNV_pic/Gender_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 540, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLNV_pic/Adr_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 540, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/Phone_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 540, 50));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLKH_pic/DateOfBirth_Bgr.png"))); // NOI18N
        NV_Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 540, 50));

        NV_Table.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        NV_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Staff ID", "Full Name", "Gender", "Address", "Phone Number", "Date Of Birth", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NV_Table.setFocusable(false);
        NV_Table.setRowHeight(25);
        NV_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NV_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        NV_Table.getTableHeader().setResizingAllowed(false);
        NV_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(NV_Table);

        NV_Panel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 880, 390));

        TabPanel.addTab("tab5", NV_Panel);

        LSDP_Panel.setBackground(new java.awt.Color(250, 249, 248));
        LSDP_Panel.setPreferredSize(new java.awt.Dimension(940, 900));
        LSDP_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("UTM Avo", 1, 24)); // NOI18N
        jLabel22.setText("RENTAL HISTORY");
        LSDP_Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 70));

        jButton1.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        jButton1.setText("Refesh");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        LSDP_Panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 30));

        LSDP_Table.setFont(new java.awt.Font("UTM Avo", 0, 12)); // NOI18N
        LSDP_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Room ID", "Customer ID", "Staff ID", "Check In Date", "Check Out Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        LSDP_Table.setFocusable(false);
        LSDP_Table.setRowHeight(25);
        LSDP_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LSDP_Table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LSDP_Table.getTableHeader().setResizingAllowed(false);
        LSDP_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(LSDP_Table);

        LSDP_Panel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 880, 760));

        TabPanel.addTab("tab6", LSDP_Panel);

        mainPanel.add(TabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -30, 940, 930));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQLPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseEntered
        btnQLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQLP2.png")));
    }//GEN-LAST:event_btnQLPMouseEntered

    private void btnQLPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseExited
        btnQLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQLP1.png")));
    }//GEN-LAST:event_btnQLPMouseExited

    private void btnQLKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseEntered
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQKH2.png")));
    }//GEN-LAST:event_btnQLKHMouseEntered

    private void btnQLKHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseExited
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQKH1.png")));
    }//GEN-LAST:event_btnQLKHMouseExited

    private void btnQLNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseEntered
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQNV2.png")));
    }//GEN-LAST:event_btnQLNVMouseEntered

    private void btnQLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseExited
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnQNV1.png")));
    }//GEN-LAST:event_btnQLNVMouseExited

    private void btnDXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDXMouseEntered
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnDX2.png")));
    }//GEN-LAST:event_btnDXMouseEntered

    private void btnDXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDXMouseExited
        btnDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnDX1.png")));
    }//GEN-LAST:event_btnDXMouseExited

    private void btnDXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDXMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_btnDXMouseClicked

// Màn hình chính
    
    private void btnQLPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLPMouseClicked
        TabPanel.setSelectedComponent(QLP_Panel);
    }//GEN-LAST:event_btnQLPMouseClicked

    private void btnQLKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMouseClicked
        TabPanel.setSelectedComponent(KH_Panel);
    }//GEN-LAST:event_btnQLKHMouseClicked

    private void btnQLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMouseClicked
        TabPanel.setSelectedComponent(NV_Panel);
    }//GEN-LAST:event_btnQLNVMouseClicked

    private void btnLSDPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLSDPMouseClicked
        TabPanel.setSelectedComponent(LSDP_Panel);
    }//GEN-LAST:event_btnLSDPMouseClicked

    private void btnLSDPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLSDPMouseEntered
        btnLSDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnLSP2.png")));
    }//GEN-LAST:event_btnLSDPMouseEntered

    private void btnLSDPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLSDPMouseExited
        btnLSDP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnLSP1.png")));
    }//GEN-LAST:event_btnLSDPMouseExited

    private void btnINFOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINFOMouseClicked
        TabPanel.setSelectedComponent(Info_Panel);
    }//GEN-LAST:event_btnINFOMouseClicked

    private void btnINFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINFOMouseEntered
        btnINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnINFO2.png")));
    }//GEN-LAST:event_btnINFOMouseEntered

    private void btnINFOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnINFOMouseExited
        btnINFO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnINFO1.png")));
    }//GEN-LAST:event_btnINFOMouseExited

    private void btnDMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseEntered
        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnDMK2.png")));
    }//GEN-LAST:event_btnDMKMouseEntered

    private void btnDMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseExited
        btnDMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/btnDMK1.png")));
    }//GEN-LAST:event_btnDMKMouseExited

    private void btnDMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMKMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DMK_Panel().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnDMKMouseClicked

//Quản lý phòng

    private void btnFind_PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_PMouseEntered
        btnFind_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind2.png")));
    }//GEN-LAST:event_btnFind_PMouseEntered

    private void btnFind_PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_PMouseExited
        btnFind_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind1.png")));
    }//GEN-LAST:event_btnFind_PMouseExited

    private void btnFind_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_PMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFind_PMouseClicked

    private void btnUpdate_PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_PMouseEntered
        btnUpdate_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd2.png")));
    }//GEN-LAST:event_btnUpdate_PMouseEntered

    private void btnUpdate_PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_PMouseExited
        btnUpdate_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd1.png")));
    }//GEN-LAST:event_btnUpdate_PMouseExited

    private void btnUpdate_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_PMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate_PMouseClicked

    private void btnCheckIn_PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckIn_PMouseEntered
        btnCheckIn_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnCkIN2.png")));
    }//GEN-LAST:event_btnCheckIn_PMouseEntered

    private void btnCheckIn_PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckIn_PMouseExited
        btnCheckIn_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnCkIN1.png")));
    }//GEN-LAST:event_btnCheckIn_PMouseExited

    private void btnCheckIn_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckIn_PMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckIn_PMouseClicked

    private void btnCheckOut_PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckOut_PMouseEntered
        btnCheckOut_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnCkO2.png")));
    }//GEN-LAST:event_btnCheckOut_PMouseEntered

    private void btnCheckOut_PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckOut_PMouseExited
       btnCheckOut_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnCkO1.png")));
    }//GEN-LAST:event_btnCheckOut_PMouseExited

    private void btnBook_PMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_PMouseEntered
       btnBook_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnBook2.png")));
    }//GEN-LAST:event_btnBook_PMouseEntered

    private void btnBook_PMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_PMouseExited
        btnBook_P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnBook1.png")));
    }//GEN-LAST:event_btnBook_PMouseExited

    private void btnBook_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBook_PMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking_Panel().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnBook_PMouseClicked

    private void btnCheckOut_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckOut_PMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckOut_PMouseClicked

    private void LogoLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoLableMouseClicked
        TabPanel.setSelectedComponent(Main_Panel);
    }//GEN-LAST:event_LogoLableMouseClicked

//Quản lý khách hàng
    
    private void btnFind_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_KHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFind_KHMouseClicked

    private void btnFind_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_KHMouseEntered
        btnFind_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind2.png")));
    }//GEN-LAST:event_btnFind_KHMouseEntered

    private void btnFind_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_KHMouseExited
        btnFind_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind1.png")));
    }//GEN-LAST:event_btnFind_KHMouseExited

    private void btnAdd_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_KHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd_KHMouseClicked

    private void btnAdd_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_KHMouseEntered
        btnAdd_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnAdd2.png")));
    }//GEN-LAST:event_btnAdd_KHMouseEntered

    private void btnAdd_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_KHMouseExited
        btnAdd_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnAdd1.png")));
    }//GEN-LAST:event_btnAdd_KHMouseExited

    private void btnUpdate_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_KHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate_KHMouseClicked

    private void btnUpdate_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_KHMouseEntered
        btnUpdate_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd2.png")));
    }//GEN-LAST:event_btnUpdate_KHMouseEntered

    private void btnUpdate_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_KHMouseExited
        btnUpdate_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd1.png")));
    }//GEN-LAST:event_btnUpdate_KHMouseExited

    private void btnDelete_KHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete_KHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete_KHMouseClicked

    private void btnDelete_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete_KHMouseEntered
        btnDelete_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnDel2.png")));
    }//GEN-LAST:event_btnDelete_KHMouseEntered

    private void btnDelete_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete_KHMouseExited
        btnDelete_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnDel1.png")));
    }//GEN-LAST:event_btnDelete_KHMouseExited

// Quản lý nhân viên    
    
    private void btnFind_NVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_NVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFind_NVMouseClicked

    private void btnFind_NVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_NVMouseEntered
        btnFind_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind2.png")));
    }//GEN-LAST:event_btnFind_NVMouseEntered

    private void btnFind_NVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFind_NVMouseExited
        btnFind_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnFind1.png")));
    }//GEN-LAST:event_btnFind_NVMouseExited

    private void btnAdd_NVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_NVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd_NVMouseClicked

    private void btnAdd_NVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_NVMouseEntered
        btnAdd_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnAdd2.png")));
    }//GEN-LAST:event_btnAdd_NVMouseEntered

    private void btnAdd_NVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd_NVMouseExited
        btnAdd_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnAdd1.png")));
    }//GEN-LAST:event_btnAdd_NVMouseExited

    private void btnUpdate_NVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_NVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate_NVMouseClicked

    private void btnUpdate_NVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_NVMouseEntered
        btnUpdate_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd2.png")));
    }//GEN-LAST:event_btnUpdate_NVMouseEntered

    private void btnUpdate_NVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate_NVMouseExited
        btnUpdate_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnUpd1.png")));
    }//GEN-LAST:event_btnUpdate_NVMouseExited

    private void btnDelete_NVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete_NVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete_NVMouseClicked

    private void btnDelete_NVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete_NVMouseEntered
        btnDelete_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnDel2.png")));
    }//GEN-LAST:event_btnDelete_NVMouseEntered

    private void btnDelete_NVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete_NVMouseExited
        btnDelete_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pic/QLP_pic/btnDel1.png")));
    }//GEN-LAST:event_btnDelete_NVMouseExited

//etc
    
    private void ID_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ID_TextFieldFocusGained
        if(ID_TextField.getText().equals("Room ID")){
            ID_TextField.setText("");
        }
    }//GEN-LAST:event_ID_TextFieldFocusGained

    private void ID_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ID_TextFieldFocusLost
        if(ID_TextField.getText().isEmpty()) {
            ID_TextField.setText("Room ID");
        }
    }//GEN-LAST:event_ID_TextFieldFocusLost

    private void BookID_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BookID_TextFieldFocusGained
        if(BookID_TextField.getText().equals("Booking ID")){
            BookID_TextField.setText("");
        }
    }//GEN-LAST:event_BookID_TextFieldFocusGained

    private void BookID_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BookID_TextFieldFocusLost
        if(BookID_TextField.getText().isEmpty()) {
            BookID_TextField.setText("Booking ID");
        }
    }//GEN-LAST:event_BookID_TextFieldFocusLost

    private void CustomerID_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CustomerID_TextFieldFocusGained
        if(CustomerID_TextField.getText().equals("Customer ID")){
            CustomerID_TextField.setText("");
        }
    }//GEN-LAST:event_CustomerID_TextFieldFocusGained

    private void CustomerID_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CustomerID_TextFieldFocusLost
        if(CustomerID_TextField.getText().isEmpty()) {
            CustomerID_TextField.setText("Customer ID");
        }
    }//GEN-LAST:event_CustomerID_TextFieldFocusLost

    private void Name_KH_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_KH_TextFieldFocusGained
        if(Name_KH_TextField.getText().equals("Full Name")){
            Name_KH_TextField.setText("");
        }
    }//GEN-LAST:event_Name_KH_TextFieldFocusGained

    private void Name_KH_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_KH_TextFieldFocusLost
        if(Name_KH_TextField.getText().isEmpty()) {
            Name_KH_TextField.setText("Full Name");
        }
    }//GEN-LAST:event_Name_KH_TextFieldFocusLost

    private void CCCD_KH_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CCCD_KH_TextFieldFocusGained
        if(CCCD_KH_TextField.getText().equals("CCCD")){
            CCCD_KH_TextField.setText("");
        }
    }//GEN-LAST:event_CCCD_KH_TextFieldFocusGained

    private void CCCD_KH_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CCCD_KH_TextFieldFocusLost
        if(CCCD_KH_TextField.getText().isEmpty()) {
            CCCD_KH_TextField.setText("CCCD");
        }
    }//GEN-LAST:event_CCCD_KH_TextFieldFocusLost

    private void Phone_KH_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_KH_TextFieldFocusGained
        if(Phone_KH_TextField.getText().equals("Phone Number")){
            Phone_KH_TextField.setText("");
        }
    }//GEN-LAST:event_Phone_KH_TextFieldFocusGained

    private void Phone_KH_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_KH_TextFieldFocusLost
        if(Phone_KH_TextField.getText().isEmpty()) {
            Phone_KH_TextField.setText("Phone Number");
        }
    }//GEN-LAST:event_Phone_KH_TextFieldFocusLost

    private void DOBirth_KH_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBirth_KH_TextFieldFocusGained
        if(DOBirth_KH_TextField.getText().equals("Date Of Birth")){
            DOBirth_KH_TextField.setText("");
        }
    }//GEN-LAST:event_DOBirth_KH_TextFieldFocusGained

    private void DOBirth_KH_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBirth_KH_TextFieldFocusLost
       if(DOBirth_KH_TextField.getText().isEmpty()) {
            DOBirth_KH_TextField.setText("Date Of Birth");
        }
    }//GEN-LAST:event_DOBirth_KH_TextFieldFocusLost

    private void CusID_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CusID_TextFieldFocusGained
        if(CusID_TextField.getText().equals("Customer ID")){
            CusID_TextField.setText("");
        }
    }//GEN-LAST:event_CusID_TextFieldFocusGained

    private void CusID_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CusID_TextFieldFocusLost
        if(CusID_TextField.getText().isEmpty()) {
            CusID_TextField.setText("Customer ID");
        }
    }//GEN-LAST:event_CusID_TextFieldFocusLost

    private void StaffID_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StaffID_TextFieldFocusGained
        if(StaffID_TextField.getText().equals("Staff ID")){
            StaffID_TextField.setText("");
        }
    }//GEN-LAST:event_StaffID_TextFieldFocusGained

    private void StaffID_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_StaffID_TextFieldFocusLost
        if(StaffID_TextField.getText().isEmpty()) {
            StaffID_TextField.setText("Staff ID");
        }
    }//GEN-LAST:event_StaffID_TextFieldFocusLost

    private void Name_NV_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_NV_TextFieldFocusGained
        if(Name_NV_TextField.getText().equals("Full Name")){
            Name_NV_TextField.setText("");
        }
    }//GEN-LAST:event_Name_NV_TextFieldFocusGained

    private void Name_NV_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_NV_TextFieldFocusLost
        if(Name_NV_TextField.getText().isEmpty()) {
            Name_NV_TextField.setText("Full Name");
        }
    }//GEN-LAST:event_Name_NV_TextFieldFocusLost

    private void Gender_NV_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Gender_NV_TextFieldFocusGained
        if(Gender_NV_TextField.getText().equals("Gender")){
            Gender_NV_TextField.setText("");
        }
    }//GEN-LAST:event_Gender_NV_TextFieldFocusGained

    private void Gender_NV_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Gender_NV_TextFieldFocusLost
        if(Gender_NV_TextField.getText().isEmpty()) {
            Gender_NV_TextField.setText("Gender");
        }
    }//GEN-LAST:event_Gender_NV_TextFieldFocusLost

    private void Adr_NV_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Adr_NV_TextFieldFocusGained
        if(Adr_NV_TextField.getText().equals("Address")){
            Adr_NV_TextField.setText("");
        }
    }//GEN-LAST:event_Adr_NV_TextFieldFocusGained

    private void Adr_NV_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Adr_NV_TextFieldFocusLost
        if(Adr_NV_TextField.getText().isEmpty()) {
            Adr_NV_TextField.setText("Address");
        }
    }//GEN-LAST:event_Adr_NV_TextFieldFocusLost

    private void Phone_NV_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_NV_TextFieldFocusGained
        if(Phone_NV_TextField.getText().equals("Phone Number")){
            Phone_NV_TextField.setText("");
        }
    }//GEN-LAST:event_Phone_NV_TextFieldFocusGained

    private void Phone_NV_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Phone_NV_TextFieldFocusLost
        if(Phone_NV_TextField.getText().isEmpty()) {
            Phone_NV_TextField.setText("Phone Number");
        }
    }//GEN-LAST:event_Phone_NV_TextFieldFocusLost

    private void DOBirth_NV_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBirth_NV_TextFieldFocusGained
        if(DOBirth_NV_TextField.getText().equals("Date Of Birth")){
            DOBirth_NV_TextField.setText("");
        }
    }//GEN-LAST:event_DOBirth_NV_TextFieldFocusGained

    private void DOBirth_NV_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBirth_NV_TextFieldFocusLost
        if(DOBirth_NV_TextField.getText().isEmpty()) {
            DOBirth_NV_TextField.setText("Date Of Birth");
        }
    }//GEN-LAST:event_DOBirth_NV_TextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
//    Employee_BUS em_BUS = new Employee_BUS();
//    public void setUpTypeOfTable(){
//        DefaultTableModel model= (DefaultTableModel)NV_Table.getModel();
//        model.addColumn("ID");
//        model.addColumn("Full Name");
//        model.addColumn("Gender");
//        model.addColumn("DateOfBird");
//        model.addColumn("Phone Number");
//        model.addColumn("Address");
//        model.addColumn("Department");
//        
//        
//
//    }
//    public void GetDataFromDTBToStaffTable(){
//        List<Employee_DTO> list_em = new ArrayList<>();
//        DefaultTableModel model= (DefaultTableModel)NV_Table.getModel();
//        list_em = em_BUS.SelectData("select * from Staff");
//        Object[] row= new Object[7];
//        list_em.forEach((Employee_DTO em) -> {
//            row= new Object[7];
//            row[0]=em.getStaffId();
//            row[1]=em.getFullName();
//            row[2]=em.getGender();
//            row[3]=em.getDateOfBird();
//            row[4]=em.getPhoneNumber();
//            row[5]=em.getAddress();
//            row[6]=em.getDepartment();
//            model.addRow(row);  
//
//
//        });
//        ;
//    }
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adr_NV_TextField;
    private javax.swing.JLabel BackGr;
    private javax.swing.JTextField BookID_TextField;
    private javax.swing.JTextField CCCD_KH_TextField;
    private javax.swing.JTextField CusID_TextField;
    private javax.swing.JTextField CustomerID_TextField;
    private javax.swing.JTextField DOBirth_KH_TextField;
    private javax.swing.JTextField DOBirth_NV_TextField;
    private javax.swing.JComboBox<String> DePart_NV_TextField;
    private javax.swing.JTextField Gender_NV_TextField;
    private javax.swing.JLabel ID_Backgr;
    private javax.swing.JLabel ID_Text;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JPanel Info_Panel;
    private javax.swing.JPanel KH_Panel;
    private javax.swing.JTable KH_Table;
    private javax.swing.JPanel LSDP_Panel;
    private javax.swing.JTable LSDP_Table;
    private javax.swing.JLabel LogoLable;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel NV_Panel;
    private javax.swing.JTable NV_Table;
    private javax.swing.JLabel Name_Backgr;
    private javax.swing.JTextField Name_KH_TextField;
    private javax.swing.JTextField Name_NV_TextField;
    private javax.swing.JLabel Name_Text;
    private javax.swing.JTextField Phone_KH_TextField;
    private javax.swing.JTextField Phone_NV_TextField;
    private javax.swing.JTable Phong_Table;
    private javax.swing.JPanel QLP_Panel;
    private javax.swing.JLabel SDT_Backgr;
    private javax.swing.JLabel SDT_Text;
    private javax.swing.JTextField StaffID_TextField;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JComboBox<String> TypeRoomComboBox;
    private javax.swing.JLabel btnAdd_KH;
    private javax.swing.JLabel btnAdd_NV;
    private javax.swing.JLabel btnBook_P;
    private javax.swing.JLabel btnCheckIn_P;
    private javax.swing.JLabel btnCheckOut_P;
    private javax.swing.JLabel btnClear_KH;
    private javax.swing.JLabel btnClear_NV;
    private javax.swing.JLabel btnClear_P;
    private javax.swing.JLabel btnDMK;
    private javax.swing.JLabel btnDX;
    private javax.swing.JLabel btnDelete_KH;
    private javax.swing.JLabel btnDelete_NV;
    private javax.swing.JLabel btnFind_KH;
    private javax.swing.JLabel btnFind_NV;
    private javax.swing.JLabel btnFind_P;
    private javax.swing.JLabel btnINFO;
    private javax.swing.JLabel btnLSDP;
    private javax.swing.JLabel btnQLKH;
    private javax.swing.JLabel btnQLNV;
    private javax.swing.JLabel btnQLP;
    private javax.swing.JLabel btnUpdate_KH;
    private javax.swing.JLabel btnUpdate_NV;
    private javax.swing.JLabel btnUpdate_P;
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
